version: "3.9"

services:
  db:
    image: postgres:16
    container_name: job-hunt-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - db
    command: >
      -url=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./postgres/migrations:/flyway/sql

  api:
    image: ghcr.io/mastodonus/application-tracker-api:latest
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "5333"
    networks:
      - application-tracker-network

  client:
    image: ghcr.io/mastodonus/application-tracker-client:latest
    container_name: client
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - api
    expose:
      - "80"
    networks:
      - application-tracker-network

networks:
  application-tracker-network:
    driver: bridge