services:
  db:
    image: postgres:16
    container_name: job-hunt-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - db
    command: >
      -url=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      migrate
    volumes:
      - ./postgres/migrations:/flyway/sql
  
  api:
    build: ./api
    ports:
      - "${API_PORT}:5333"
    env_file:
      - .env
    depends_on:
      - flyway
  
  client:
    build: ./client
    ports:
      - "${CLIENT_PORT}:80"
    env_file:
      - .env
      - client/.env
    depends_on:
      - api